name: EligiusConnector
version: '${projectVersion}'
main: com.makrozai.eligiusconnector.EligiusConnector
api-version: '1.21'
authors: [ makrozai ]
description: The ultimate Discord-Minecraft bridge plugin
softdepend: [PlaceholderAPI]
libraries:
  - com.zaxxer:HikariCP:5.1.0

commands:
  eligiusconnector:
    description: Main command for EligiusConnector
    aliases: [connector, ec]
  verify:
    description: Link your Minecraft account with Discord
    usage: /verify <code>
  unlink:
    description: Unlink your Minecraft account from Discord
    usage: /unlink [player]
  events:
    description: Manage custom events
    usage: /events <list|start|stop> [id]
    aliases: [event]
  chat:
    description: Send a message to Discord
    usage: /chat <message>

permissions:
  connector.verify:
    description: Allows linking account
    default: true
  connector.unlink.self:
    description: Allows unlinking own account
    default: true
  connector.unlink.other:
    description: Allows unlinking other players
    default: op
  connector.console:
    description: Allows executing console commands
    default: false
  connector.chat.send:
    description: Allows sending chat messages
    default: true
  connector.chat:
    description: Allows using /chat command
    default: true
  connector.events:
    description: Manage custom events
    default: op
  connector.notifications.receive:
    description: Receive notifications
    default: true
  connector.reload:
    description: Reload plugin configuration
    default: op
  connector.admin:
    description: Admin commands
    default: op
